Repository CA-G12/car-trade, pull requests merged in 2022-11, with the labels that each got.

#118 Add scripts for heroku deploy
  package.json
  server/.eslintrc.js
  server/package.json
  server/src/app.ts
  server/tsconfig.json
Labels: awaiting review

#125 Nav bar
  client/src/App.tsx
  client/src/components/HeroSection/index.tsx
  client/src/components/NavBar/index.tsx
  client/src/context.tsx
  client/src/index.css
  server/src/routes/auth.ts
Labels: awaiting review

#131 build: send email
  server/package-lock.json
  server/package.json
  server/src/controllers/cars.ts
  server/src/controllers/index.ts
  server/src/helpers/index.ts
  server/src/helpers/sendEmail.ts
  server/src/routes/cars.ts
  server/src/validation/updateCarSchema.ts
Labels: awaiting review

#133 121 private routes
  client/src/interfaces/index.ts
  client/src/routes/index.tsx
  client/src/routes/privateRoutes.tsx
Labels: awaiting review

#138 fix: edit styles admin login
  client/src/pages/AdminLogin/styles.css
Labels: awaiting review

#137 Create upload images functionality
  client/package-lock.json
  client/package.json
  client/src/components/UpLoadImages/index.tsx
  client/src/components/snackbar.tsx
  client/src/firebase/firebaseConfig.ts
Labels: awaiting review

#139 132 cars page responsive
  client/src/components/CarCard/index.tsx
  client/src/components/CarCard/style.css
  client/src/components/CarsFilter/style.css
  client/src/components/FilterSideInMobile.tsx
  client/src/pages/Cars/index.tsx
  client/src/pages/Cars/style.css
Labels: awaiting review

#141 check car modal
  client/src/assets/data/features.ts
  client/src/components/CarAdminModule.tsx
  client/src/components/CarInfoSection/index.tsx
  client/src/components/NavBar/index.tsx
  client/src/components/requestsTable/row.tsx
  client/src/components/sendRequsetModel/Form.tsx
  client/src/components/sendRequsetModel/index.tsx
  client/src/components/stepper.tsx
  client/src/context.tsx
  client/src/helpers/validationSchema.ts
  client/src/index.css
  client/src/interfaces/index.ts
  client/src/pages/CheckCar/index.tsx
  client/src/routes/index.tsx
  server/__tests__/cars.ts
  server/src/controllers/auth.ts
  server/src/db/config/fakedata.json
  server/src/db/models/car.ts
  server/src/validation/updateCarSchema.ts
Labels: awaiting review

#134 fix: make landing page responsive
  client/src/components/HeroSection/index.tsx
  client/src/components/HeroSection/style.css
  client/src/components/HomeCard/index.tsx
  client/src/components/HomeCard/style.css
  client/src/components/HomeCardSection/index.tsx
  client/src/components/HomeCardSection/style.css
  client/src/components/brand/index.tsx
  client/src/components/brand/style.css
Labels: awaiting review, changes requested

#136 135 not found pages
  client/package-lock.json
  client/src/assets/index.ts
  client/src/assets/notFound.svg
  client/src/components/HeroSection/style.css
  client/src/pages/Errors/notFound.tsx
  client/src/pages/Errors/style.css
  client/src/pages/Errors/styles.css
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: changes requested

#145 build: get user car that want sell and his info
  server/src/controllers/cars.ts
  server/src/controllers/index.ts
  server/src/interfaces/index.ts
  server/src/routes/cars.ts
  server/src/services/cars.ts
  server/src/services/index.ts
Labels: approved

#149 fix bug in snackbar
  client/src/components/NavBar/index.tsx
  client/src/components/requestsTable/index.tsx
  client/src/components/sendRequsetModel/Form.tsx
Labels: awaiting review

#162 158 handle buy request
  client/src/components/StripForm/index.tsx
  client/src/components/carControll/index.tsx
  server/src/controllers/cars.ts
Labels: awaiting review

#161 fix: style in login signup page
  client/src/pages/Login/style.css
Labels: awaiting review

#155 Send emails to the user
  client/src/index.css
  server/__tests__/cars.ts
  server/src/controllers/cars.ts
  server/src/db/config/fakedata.json
  server/src/helpers/emailTemplate.ts
  server/src/helpers/sendEmail.ts
Labels: awaiting review

#168 fix: function in filter
  client/src/Hooks/UseFIlter.tsx
  client/src/components/CarsFilter/index.tsx
Labels: awaiting review

#171 redirect user to prev location in case of login and signup
  client/src/components/NavBar/index.tsx
  client/src/components/carControll/index.tsx
  client/src/pages/AdminLogin/index.tsx
  client/src/pages/Login/index.tsx
  client/src/routes/privateRoutes.tsx
Labels: awaiting review

#170 fix: space navbar
  client/src/components/NavBar/index.tsx
  client/src/components/snackbar.tsx
  client/src/pages/Cars/style.css
Labels: awaiting review

#164 Build functionality to storing images URLs in database
  client/src/components/CarsFilter/index.tsx
  client/src/components/UpLoadImages/index.tsx
  client/src/components/UpLoadImages/style.css
  client/src/components/requestsTable/index.tsx
  client/src/components/requestsTable/row.tsx
  client/src/components/requestsTable/style.css
  client/src/components/sendRequsetModel/Form.tsx
  client/src/components/stepper.tsx
  client/src/interfaces/index.ts
  server/__tests__/cars.ts
  server/src/controllers/cars.ts
  server/src/controllers/index.ts
  server/src/db/config/fakedata.json
  server/src/db/models/image.ts
  server/src/interfaces/index.ts
  server/src/routes/cars.ts
  server/src/services/cars.ts
  server/src/services/index.ts
Labels: awaiting review

#175 change faild size from sell car model
  client/src/components/sendRequsetModel/Form.tsx
  client/src/components/sendRequsetModel/index.tsx
  client/src/components/sendRequsetModel/style.css
Labels: awaiting review

#183 Apply some edits on navbar
  client/src/components/NavBar/index.tsx
Labels: awaiting review

#185 Edit texts and style the landing page
  client/src/assets/BMW.jpg
  client/src/assets/index.ts
  client/src/components/HomeCard/style.css
  client/src/components/brand/index.tsx
  client/src/components/brand/style.css
  client/src/pages/Landing/index.tsx
  client/src/pages/Landing/style.css
Labels: awaiting review

#188 Fix style of car info page
  client/src/components/CarInfoSection/index.tsx
  client/src/components/CarInfoSection/style.css
Labels: awaiting review

#187 178 add fuel
  client/src/components/stepper.tsx
Labels: awaiting review

#197 194 sell car model responsive
  client/src/components/FilterSideInMobile.tsx
  client/src/components/sendRequsetModel/Form.tsx
  client/src/components/sendRequsetModel/index.tsx
Labels: awaiting review

#193 fix: put car card in midle in mobile and tablet
  client/src/components/FilterSideInMobile.tsx
Labels: awaiting review

#203 Make sign up and log in responsive
  client/src/components/signUpForm/style.css
  client/src/helpers/validationSchema.ts
  client/src/pages/Login/style.css
Labels: awaiting review

#190 Fix Admin login style and make it responsive
  client/src/pages/AdminLogin/styles.css
Labels: awaiting review

#199 fix: deploy secripts
  package-lock.json
  package.json
  server/package.json
Labels: awaiting review

#202 fix: return user data when signup
  server/src/controllers/auth.ts
  server/src/services/auth.ts
Labels: awaiting review

#207 Fix Stripe validation
  client/src/components/StripForm/index.tsx
  server/example.env
Labels: awaiting review

#210 fix cars container style
  client/src/pages/Cars/style.css
Labels: awaiting review

#204 Create readme.md file
  README.md
Labels: awaiting review

#212 Remove signup and login buttons from admin login page
  client/src/components/NavBar/index.tsx
Labels: awaiting review

#217 fix filter by mileage feature
  client/src/Hooks/UseFIlter.tsx
  client/src/components/CarsFilter/index.tsx
Labels: awaiting review

#215 Remove filter by model feature
  client/src/Hooks/UseFIlter.tsx
  client/src/assets/data/models.json
  client/src/components/CarsFilter/index.tsx
Labels: approved

#218 [README ] Remove unused links from contents table
  README.md
Labels: done
