Repository CA-G12/car-trade, pull requests merged in 2022-10, with the labels that each got.

#3 create file structure for server side and install almost packeg we w…
  src/.eslintrc.js
  src/.gitignore
  src/__test__/.gitkeep
  src/app.ts
  src/config/.gitkeep
  src/controllers/.gitkeep
  src/db/.gitkeep
  src/helpers/.gitkeep
  src/index.ts
  src/interfaces/.gitkeep
  src/middlewares/.gitkeep
  src/models/.gitkeep
  src/package-lock.json
  src/package.json
  src/routes/.gitkeep
  src/tsconfig.json
  src/validation/.gitkeep
Labels: approved

#4 create file structure for client side
  clients/.eslintrc.json
  clients/.gitignore
  clients/package-lock.json
  clients/package.json
  clients/public/index.html
  clients/public/logo.jpg
  clients/src/App.tsx
  clients/src/assets/.gitkeep
  clients/src/components/.gitkeep
  clients/src/cssReset.css
  clients/src/helpers/.gitkeep
  clients/src/index.css
  clients/src/index.tsx
  clients/src/layouts/.gitkeep
  clients/src/pages/.gitkeep
  clients/src/services/.gitkeep
  clients/tsconfig.json
  package-lock.json
Labels: awaiting review

#11 build: config files
  src/.gitignore
  src/config/build.sql
  src/config/connection.ts
  src/example.env
  src/package-lock.json
Labels: approved

#14 create cars model
  client/package-lock.json
  package-lock.json
  src/config/.gitkeep
  src/models/.gitkeep
  src/models/Cars.ts
Labels: approved

#16 build: customer's model
  src/config/connection.ts
  src/models/customers.ts
Labels: changes requested

#22 GitHub action
  .github/workflows/node.js.yml
  package.json
  src/__test__/.gitkeep
  src/__test__/fackeTest.test.ts
  src/jest.config.js
  src/package-lock.json
  src/package.json
Labels: awaiting review

#26 fix: rearrange server files
  package.json
  server/.eslintrc.js
  server/.gitignore
  server/__tests__/fackeTest.ts
  server/example.env
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db/config/build.sql
  server/src/db/config/connection.ts
  server/src/db/models/admin.ts
  server/src/db/models/car.ts
  server/src/db/models/customer.ts
  server/src/db/models/image.ts
  server/src/db/models/index.ts
  server/src/db/seeders/.gitkeep
  server/src/helpers/.gitkeep
  server/src/index.ts
  server/src/interfaces/.gitkeep
  server/src/middlewares/.gitkeep
  server/src/routes/.gitkeep
  server/src/validation/.gitkeep
  server/tsconfig.json
  src/__test__/fackeTest.test.ts
  src/validation/.gitkeep
Labels: approved

#27 build: handle routing in front
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/pages/AdminLogin/index.tsx
  client/src/pages/AdminLogin/styles.css
  client/src/pages/Car/index.tsx
  client/src/pages/Car/styles.css
  client/src/pages/DashBoard/RecentRequests.tsx
  client/src/pages/DashBoard/ToCheckRequests.tsx
  client/src/pages/DashBoard/index.tsx
  client/src/pages/DashBoard/styles.css
  client/src/pages/Errors/Error.tsx
  client/src/pages/Errors/notFound.tsx
  client/src/pages/Errors/styles.css
  client/src/pages/Landing/index.tsx
  client/src/pages/Landing/styles.css
  client/src/pages/Login/index.tsx
  client/src/pages/Login/styles.css
  client/src/pages/Profile/index.tsx
  client/src/pages/Profile/styles.css
  client/src/pages/Search/index.tsx
  client/src/pages/Search/styles.css
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/styles.css
  client/src/routes/index.tsx
Labels: approved

#24 fix: setups express server
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/index.ts
  server/src/routes/routes.ts
Labels: approved

#29 ci: middleware handel clint error , middleware handle server error
  server/package-lock.json
  server/package.json
  server/src/app.ts
Labels: awaiting review

#35 hero setion in landing page
  .gitignore
  client/package-lock.json
  client/src/assets/banner.jpg
  client/src/components/HeroSection/index.tsx
  client/src/components/HeroSection/style.css
  client/src/index.css
  client/src/pages/Landing/index.tsx
Labels: awaiting review

#36 Created fake data and a function that will build data in database
  commitlint.config.js
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/db/config/buildFakeData.ts
  server/src/db/config/fakedata.json
  server/src/db/models/index.ts
  server/tsconfig.json
Labels: changes requested

#39 build: create card home section realates #38
  client/src/components/HomeCard/style.css
  client/src/components/HomeCardSection/index.tsx
  client/src/components/HomeCardSection/style.css
Labels: approved

#47 build: search car card relates #45
  client/src/App.tsx
  client/src/components/CarCard/index.tsx
  client/src/components/CarCard/style.css
  client/src/custom.d.ts
  client/src/pages/Search/index.tsx
Labels: awaiting review

#52 build: create send request model relates #48
  client/package-lock.json
  client/package.json
  client/src/brand.json
  client/src/components/brand/index.tsx
  client/src/components/sendRequsetModel/Form.tsx
  client/src/components/sendRequsetModel/index.tsx
  client/src/helpers/validationSchema.ts
  client/src/pages/Profile/index.tsx
Labels: changes requested

#53 build: login page
  client/public/images/2.jpg
  client/src/assets/index.ts
  client/src/components/sendRequsetModel/Form.tsx
  client/src/helpers/validationSchema.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.css
  client/src/pages/Login/styles.css
  client/src/services/axiosCongif.ts
Labels: changes requested

#57 build: car slider
  client/package-lock.json
  client/package.json
  client/src/components/CarSlider/index.tsx
  client/src/components/CarSlider/style.css
  client/src/pages/Car/index.tsx
Labels: changes requested

#65 fix: return car images with car information relates #63
  server/__tests__/cars.ts
  server/src/services/cars/allCars.ts
Labels: awaiting review

#59 Created filter component
  client/.eslintrc.js
  client/package-lock.json
  client/src/brands.json
  client/src/components/CarsFilter/index.tsx
  client/src/components/CarsFilter/style.css
  client/src/components/brand/index.tsx
  client/src/components/sendRequsetModel/Form.tsx
  client/src/models.json
  client/src/pages/Cars/index.tsx
  client/src/pages/Cars/styles.css
  client/src/pages/Search/styles.css
  client/src/routes/index.tsx
  package-lock.json
  server/__tests__/cars.ts
  server/package-lock.json
  server/src/db/config/connection.ts
Labels: awaiting review

#61 build: car details
  server/__tests__/cars.ts
  server/package.json
  server/src/app.ts
  server/src/controllers/cars/getCarsById.ts
  server/src/controllers/cars/getFilteredCars.ts
  server/src/controllers/cars/index.ts
  server/src/controllers/index.ts
  server/src/routes/ExpressWrapper.ts
  server/src/routes/cars.ts
  server/src/services/cars/getCar.ts
  server/src/services/cars/index.ts
  server/src/services/index.ts
Labels: changes requested

#68 add car info section
  client/src/assets/data/features.ts
  client/src/components/CarInfoSection/index.tsx
  client/src/components/CarInfoSection/style.css
  client/src/components/HeroSection/index.tsx
  client/src/components/HeroSection/style.css
  client/src/index.css
  client/src/pages/Car/index.tsx
Labels: awaiting review

#67 66 handel search page
  client/package-lock.json
  client/package.json
  client/src/components/CarCard/index.tsx
  client/src/components/CarsFilter/index.tsx
  client/src/components/CarsFilter/style.css
  client/src/components/skeleton.tsx
  client/src/components/snackbar.tsx
  client/src/interfaces/index.ts
  client/src/pages/.gitkeep
  client/src/pages/Cars/index.tsx
  client/src/pages/Cars/style.css
  client/src/pages/Cars/styles.css
  client/src/pages/Search/index.tsx
  client/src/routes/index.tsx
  client/src/services/axiosCongif.ts
  server/__tests__/cars.ts
  server/src/controllers/cars/getFilteredCars.ts
  server/src/services/cars/allCars.ts
Labels: changes requested

#74 Verify token middleware
  server/package-lock.json
  server/package.json
  server/src/helpers/.gitkeep
  server/src/helpers/verifyToken.ts
  server/src/middlewares/.gitkeep
  server/src/middlewares/authMiddleware.ts
Labels: awaiting review

#70 Create Stripe Form
  client/package-lock.json
  client/package.json
  client/src/assets/data/brands.json
  client/src/assets/data/models.json
  client/src/components/CarInfoSection/index.tsx
  client/src/components/CarInfoSection/style.css
  client/src/components/CarsFilter/index.tsx
  client/src/components/HeroSection/index.tsx
  client/src/components/HeroSection/style.css
  client/src/components/StripForm/index.tsx
  client/src/components/StripForm/style.css
  client/src/components/carControll/index.tsx
  client/src/components/carControll/style.css
  client/src/components/sendRequsetModel/Form.tsx
  client/src/index.css
  client/src/pages/Car/index.tsx
  client/src/pages/Car/style.css
  client/src/pages/Car/styles.css
Labels: changes requested

#73 72 change car card
  client/src/components/CarCard/index.tsx
  client/src/pages/Cars/index.tsx
  client/src/pages/Cars/style.css
Labels: awaiting review

#75 fix: add list page
  client/src/components/Tabs/index.tsx
  client/src/pages/DashBoard/index.tsx
Labels: awaiting review

#79 78 update car
  .github/workflows/node.js.yml
  server/__tests__/cars.ts
  server/src/controllers/cars/index.ts
  server/src/controllers/cars/updateCars.ts
  server/src/controllers/index.ts
  server/src/routes/cars.ts
  server/src/services/cars/index.ts
  server/src/services/cars/updateCar.ts
  server/src/validation/.gitkeep
  server/src/validation/index.ts
  server/src/validation/updateCarSchema.ts
Labels: awaiting review

#89 build: handle login page
  client/package-lock.json
  client/src/pages/Login/index.tsx
  client/src/services/axiosCongif.ts
  server/__tests__/cars.ts
  server/src/controllers/login.ts
  server/src/services/index.ts
  server/src/services/login.ts
  server/src/validation/loginSchema.ts
Labels: approved

#81 fix: delete cars
  server/__tests__/cars.ts
  server/package-lock.json
  server/src/controllers/cars/deleteCarsById.ts
  server/src/controllers/cars/getCarsById.ts
  server/src/controllers/cars/index.ts
  server/src/controllers/index.ts
  server/src/middlewares/authMiddleware.ts
  server/src/routes/cars.ts
  server/src/services/cars/deleteCar.ts
  server/src/services/cars/index.ts
  server/src/services/index.ts
Labels: awaiting review

#88 requests table
  client/src/components/CarsFilter/index.tsx
  client/src/components/Tabs/index.tsx
  client/src/components/requestsTable/index.tsx
  client/src/components/requestsTable/row.tsx
  client/src/components/requestsTable/style.css
  client/src/interfaces/index.ts
  client/src/pages/Cars/index.tsx
Labels: awaiting review

#90 GET | cars with user info
  server/__tests__/cars.ts
  server/src/controllers/cars/getCarsDetails.ts
  server/src/controllers/cars/index.ts
  server/src/controllers/index.ts
  server/src/routes/cars.ts
  server/src/services/cars/allCars.ts
  server/src/services/cars/getCarsWithCustomInfo.ts
  server/src/services/cars/index.ts
  server/src/services/index.ts
Labels: changes requested

#84 Edit form for send request from the customer
  client/src/components/sendRequsetModel/Form.tsx
Labels: awaiting review

#93 create send request admin module sepper
  client/src/components/CarAdminModule.tsx
  client/src/components/requestsTable/row.tsx
  client/src/components/stepper.tsx
Labels: approved

#99 97 context provider
  client/src/App.tsx
  client/src/context.tsx
  client/src/interfaces/index.ts
  client/src/pages/Login/index.tsx
  server/__tests__/cars.ts
  server/src/controllers/login.ts
  server/src/controllers/user.ts
  server/src/routes/auth.ts
  server/src/routes/index.ts
  server/src/services/index.ts
  server/src/services/login.ts
Labels: approved

#98 dashbord requests
  client/src/components/CarAdminModule.tsx
  client/src/components/CarsFilter/index.tsx
  client/src/components/Tabs/index.tsx
  client/src/components/requestsTable/index.tsx
  client/src/components/requestsTable/row.tsx
  client/src/components/skeletons/carSkeleton.tsx
  client/src/components/skeletons/index.ts
  client/src/components/skeletons/tableSkeleton.tsx
  client/src/components/snackbar.tsx
  client/src/context.tsx
  client/src/interfaces/index.ts
  client/src/pages/Cars/index.tsx
  client/src/pages/Login/index.tsx
  client/src/services/axiosConfig.ts
Labels: awaiting review

#100 fix: post signup
  .vscode/settings.json
  server/__tests__/cars.ts
  server/src/controllers/index.ts
  server/src/controllers/signup.ts
  server/src/routes/auth.ts
  server/src/services/checkEmail.ts
  server/src/services/index.ts
  server/src/services/signup.ts
  server/src/validation/index.ts
  server/src/validation/signupSchema.ts
Labels: awaiting review

#110 refactor: file structure in the server
  client/package-lock.json
  server/package-lock.json
  server/src/controllers/auth.ts
  server/src/controllers/cars.ts
  server/src/controllers/cars/addCar.ts
  server/src/controllers/cars/deleteCarsById.ts
  server/src/controllers/cars/getCarsById.ts
  server/src/controllers/cars/getCarsDetails.ts
  server/src/controllers/cars/getFilteredCars.ts
  server/src/controllers/cars/index.ts
  server/src/controllers/cars/updateCars.ts
  server/src/controllers/index.ts
  server/src/controllers/register/index.ts
  server/src/controllers/register/login.ts
  server/src/controllers/register/signup.ts
  server/src/controllers/register/user.ts
  server/src/helpers/index.ts
  server/src/helpers/jwt.ts
  server/src/helpers/verifyToken.ts
  server/src/middlewares/authMiddleware.ts
  server/src/routes/auth.ts
  server/src/routes/cars.ts
  server/src/services/auth.ts
  server/src/services/cars.ts
  server/src/services/cars/addCar.ts
  server/src/services/cars/allCars.ts
  server/src/services/cars/deleteCar.ts
  server/src/services/cars/getCar.ts
  server/src/services/cars/getCarsWithCustomInfo.ts
  server/src/services/cars/index.ts
  server/src/services/cars/updateCar.ts
  server/src/services/index.ts
  server/src/services/register/checkEmail.ts
  server/src/services/register/index.ts
  server/src/services/register/login.ts
  server/src/services/register/signup.ts
Labels: awaiting review

#103 102 handle single car
  client/src/components/CarCard/index.tsx
  client/src/components/CarInfoSection/index.tsx
  client/src/components/CarNotFound.tsx
  client/src/components/CarSlider/index.tsx
  client/src/components/CarSlider/style.css
  client/src/components/OpenImageModel/index.tsx
  client/src/components/OpenImageModel/style.css
  client/src/components/StripForm/style.css
  client/src/components/carControll/index.tsx
  client/src/components/carControll/style.css
  client/src/components/sendRequsetModel/index.tsx
  client/src/interfaces/index.ts
  client/src/pages/Car/index.tsx
  client/src/pages/Car/style.css
  client/src/pages/Cars/index.tsx
  server/src/interfaces/.gitkeep
  server/src/interfaces/index.ts
  server/src/routes/cars.ts
Labels: awaiting review

#122 Create tests for add new selling request in most use cases
  .github/workflows/node.js.yml
  server/__tests__/cars.ts
  server/src/controllers/cars.ts
Labels: awaiting review

#117 108 admin login back
  client/src/helpers/validationSchema.ts
  client/src/pages/DashBoard/RecentRequests.tsx
  client/src/pages/DashBoard/ToCheckRequests.tsx
  client/src/pages/DashBoard/index.tsx
  client/src/routes/index.tsx
  server/__tests__/cars.ts
  server/src/controllers/auth.ts
  server/src/controllers/index.ts
  server/src/routes/auth.ts
  server/src/services/auth.ts
  server/src/services/index.ts
  server/src/validation/AdminLoginSchema.ts
Labels: awaiting review

#127 fix: return admin data from userController
  server/src/controllers/auth.ts
  server/src/services/auth.ts
  server/src/services/index.ts
Labels: awaiting review

#113 profile component
  client/src/components/ProfileInbox/SellRequest.tsx
  client/src/components/ProfileInbox/UpdateSettingForm.tsx
  client/src/components/ProfileInbox/index.tsx
  client/src/components/ProfileInbox/style.css
  client/src/helpers/validationSchema.ts
Labels: awaiting review

#123 Create sign up page with style
  client/src/components/signUpForm/index.tsx
  client/src/components/signUpForm/style.css
  client/src/helpers/validationSchema.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.css
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/styles.css
Labels: awaiting review

#107 106 admin login
  client/src/pages/AdminLogin/index.tsx
Labels: awaiting review
